

### Step 1. Import the necessary libraries

In [0]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset Euro_2012_stats_TEAM

### Step 3. Assign it to a variable called euro12.

In [0]:
euro12 = pd.read_csv("Euro_2012_stats_TEAM.csv")

In [96]:
euro12

                                                 Team  ...  Players Used
0                                             Croatia  ...          16.0
1                                      Czech Republic  ...          19.0
2                                             Denmark  ...          15.0
3                                             England  ...          16.0
4                                              France  ...          19.0
5                                             Germany  ...          17.0
6                                              Greece  ...          20.0
7                                               Italy  ...          19.0
8                                         Netherlands  ...          15.0
9                                              Poland  ...          17.0
10                                           Portugal  ...          16.0
11                                Republic of Ireland  ...          17.0
12                                             Russia  ...          16.0
13                                              Spain  ...          18.0
14                                             Sweden  ...          18.0
15                                            Ukraine  ...          18.0
16                                                NaN  ...           NaN
17                                                NaN  ...           NaN
18                                                NaN  ...           NaN
19  https://towardsdatascience.com/data-handling-u...  ...           NaN

[20 rows x 35 columns]

### Step 4. Select only the Goal column.

In [0]:
euro12['Goals conceded']

0     3.0
1     6.0
2     5.0
3     3.0
4     5.0
5     6.0
6     7.0
7     7.0
8     5.0
9     3.0
10    4.0
11    9.0
12    3.0
13    1.0
14    5.0
15    4.0
16    NaN
17    NaN
18    NaN
19    NaN
Name: Goals conceded, dtype: float64

### Step 5. How many team participated in the Euro2012?

In [0]:
print(euro12['Team'])
print(euro12.Team.count())

0                                               Croatia
1                                        Czech Republic
2                                               Denmark
3                                               England
4                                                France
5                                               Germany
6                                                Greece
7                                                 Italy
8                                           Netherlands
9                                                Poland
10                                             Portugal
11                                  Republic of Ireland
12                                               Russia
13                                                Spain
14                                               Sweden
15                                              Ukraine
16                                                  NaN
17                                                  NaN
18                                                  NaN
19    https://towardsdatascience.com/data-handling-u...
Name: Team, dtype: object
17

### Step 6. What is the number of columns in the dataset?

In [0]:
len(euro12.columns)

35

### Step 7. View only the columns Team, Yellow Cards and Red Cards and assign them to a dataframe called discipline

In [0]:
data = {'Team' : euro12['Team'], 'Red Cards' : euro12['Red Cards'], 
                           'Yellow Cards' : euro12['Yellow Cards']}
discipline = pd.DataFrame(data)
discipline


# discipline = euro12[['Team', 'Red Cards', 'Yellow Cards']]

                                                 Team  Red Cards  Yellow Cards
0                                             Croatia        0.0           9.0
1                                      Czech Republic        0.0           7.0
2                                             Denmark        0.0           4.0
3                                             England        0.0           5.0
4                                              France        0.0           6.0
5                                             Germany        0.0           4.0
6                                              Greece        1.0           9.0
7                                               Italy        0.0          16.0
8                                         Netherlands        0.0           5.0
9                                              Poland        1.0           7.0
10                                           Portugal        0.0          12.0
11                                Republic of Ireland        1.0           6.0
12                                             Russia        0.0           6.0
13                                              Spain        0.0          11.0
14                                             Sweden        0.0           7.0
15                                            Ukraine        0.0           5.0
16                                                NaN        NaN           NaN
17                                                NaN        NaN           NaN
18                                                NaN        NaN           NaN
19  https://towardsdatascience.com/data-handling-u...        NaN           NaN

### Step 8. Sort the teams by Red Cards, then to Yellow Cards

In [0]:
euro12.sort_values(by = ['Red Cards','Yellow Cards'])

                                                 Team  ...  Players Used
2                                             Denmark  ...          15.0
5                                             Germany  ...          17.0
3                                             England  ...          16.0
8                                         Netherlands  ...          15.0
15                                            Ukraine  ...          18.0
4                                              France  ...          19.0
12                                             Russia  ...          16.0
1                                      Czech Republic  ...          19.0
14                                             Sweden  ...          18.0
0                                             Croatia  ...          16.0
13                                              Spain  ...          18.0
10                                           Portugal  ...          16.0
7                                               Italy  ...          19.0
11                                Republic of Ireland  ...          17.0
9                                              Poland  ...          17.0
6                                              Greece  ...          20.0
16                                                NaN  ...           NaN
17                                                NaN  ...           NaN
18                                                NaN  ...           NaN
19  https://towardsdatascience.com/data-handling-u...  ...           NaN

[20 rows x 35 columns]

### Step 9. Calculate the mean Yellow Cards given per Team

In [47]:
euro12['Yellow Cards'].mean()

7.4375

### Step 10. Filter teams that scored more than 6 goals

In [76]:
##through selection
euro12.Team[euro12['Goals'] > 6]

5     Germany
13      Spain
Name: Team, dtype: object

In [0]:
##through filtering

### Step 11. Select the teams that start with G

In [63]:
euro12[euro12['Team'].str.match('G') == True]

      Team  Goals  Shots on target  ...  Subs on Subs off Players Used
5  Germany   10.0             32.0  ...     15.0     15.0         17.0
6   Greece    5.0              8.0  ...     12.0     12.0         20.0

[2 rows x 35 columns]

In [77]:
euro12[euro12.Team.str.startswith('G') == True]

      Team  Goals  Shots on target  ...  Subs on Subs off Players Used
5  Germany   10.0             32.0  ...     15.0     15.0         17.0
6   Greece    5.0              8.0  ...     12.0     12.0         20.0

[2 rows x 35 columns]

### Step 12. Select the first 7 columns

In [0]:
euro12.columns[0 : 8]

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork'],
      dtype='object')

In [79]:
euro12[euro12.columns[:7]]

                                                 Team  ...  Total shots (inc. Blocked)
0                                             Croatia  ...                        32.0
1                                      Czech Republic  ...                        39.0
2                                             Denmark  ...                        27.0
3                                             England  ...                        40.0
4                                              France  ...                        65.0
5                                             Germany  ...                        80.0
6                                              Greece  ...                        32.0
7                                               Italy  ...                       110.0
8                                         Netherlands  ...                        60.0
9                                              Poland  ...                        48.0
10                                           Portugal  ...                        82.0
11                                Republic of Ireland  ...                        28.0
12                                             Russia  ...                        59.0
13                                              Spain  ...                       100.0
14                                             Sweden  ...                        39.0
15                                            Ukraine  ...                        38.0
16                                                NaN  ...                         NaN
17                                                NaN  ...                         NaN
18                                                NaN  ...                         NaN
19  https://towardsdatascience.com/data-handling-u...  ...                         NaN

[20 rows x 7 columns]

### Step 13. Select all columns except the last 3.

In [80]:
euro12[euro12.columns[: -3]]

                                                 Team  ...  Red Cards
0                                             Croatia  ...        0.0
1                                      Czech Republic  ...        0.0
2                                             Denmark  ...        0.0
3                                             England  ...        0.0
4                                              France  ...        0.0
5                                             Germany  ...        0.0
6                                              Greece  ...        1.0
7                                               Italy  ...        0.0
8                                         Netherlands  ...        0.0
9                                              Poland  ...        1.0
10                                           Portugal  ...        0.0
11                                Republic of Ireland  ...        1.0
12                                             Russia  ...        0.0
13                                              Spain  ...        0.0
14                                             Sweden  ...        0.0
15                                            Ukraine  ...        0.0
16                                                NaN  ...        NaN
17                                                NaN  ...        NaN
18                                                NaN  ...        NaN
19  https://towardsdatascience.com/data-handling-u...  ...        NaN

[20 rows x 32 columns]

### Step 14. Present only the Shooting Accuracy from England, Italy and Russia

In [75]:
pd.DataFrame(euro12 , columns = ['Shooting Accuracy'] , index = ['England','Italy','Russia'])

        Shooting Accuracy
England               NaN
Italy                 NaN
Russia                NaN

In [82]:
eir = euro12[['Team','Shooting Accuracy']]
eir.loc[eir['Team'].isin(['England', 'Italy','Russia'])]

       Team Shooting Accuracy
3   England            50.00%
7     Italy            43.00%
12   Russia            22.50%

In [86]:
euro12.loc[[3,7,12],['Team','Shooting Accuracy']]

       Team Shooting Accuracy
3   England            50.00%
7     Italy            43.00%
12   Russia            22.50%

In [87]:
euro12['Shooting Accuracy'][(euro12['Team'] == 'England') | (euro12['Team'] == 'Italy') | (euro12['Team'] == 'Russia')]

3     50.00%
7     43.00%
12    22.50%
Name: Shooting Accuracy, dtype: object

In [97]:
list1 = ['Italy', 'England', 'Russia']
euro1 = [y for x,y in zip(euro12['Team'],euro12['Shooting Accuracy']) if x in list1]
euro1

['50.00%', '43.00%', '22.50%']

In [101]:
data = pd.read_csv('Euro_2012_stats_TEAM.csv', index_col = 'Team')
data.loc[['England','Italy','Russia']]['Shooting Accuracy']

Team
England    50.00%
Italy      43.00%
Russia     22.50%
Name: Shooting Accuracy, dtype: object

### Step 15. Use apply method on Goal Column to make a new column called Performance, using following conditions

1. If Goals are less than or equal to 2, peformance is **Below Avg**
2. If Goals are more than 2 and less than or equal to 5, peformance is **Average**
3. If Goals are more than 5 and less than or equal to 10, peformance is **Above Average**
4. If Goals are more than 10 then peformance is **Excellent**

In [0]:
f = lambda x: 'Below Avg' if x <= 2 else 'Avg' if x > 2 and x <= 5 else 'Above avg' if x > 5 and x <= 10 else 'Excellent'

In [107]:
euro12['Performance'] = euro12['Goals'].apply(f)
euro12[['Goals','Performance']]

    Goals Performance
0     4.0         Avg
1     4.0         Avg
2     4.0         Avg
3     5.0         Avg
4     3.0         Avg
5    10.0   Above avg
6     5.0         Avg
7     6.0   Above avg
8     2.0   Below Avg
9     2.0   Below Avg
10    6.0   Above avg
11    1.0   Below Avg
12    5.0         Avg
13   12.0   Excellent
14    5.0         Avg
15    2.0   Below Avg
16    NaN   Excellent
17    NaN   Excellent
18    NaN   Excellent
19    NaN   Excellent